name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: ${{ vars.TARGET_REPO }}
      env:
        FOLLOW_TAGS: ${{ vars.FOLLOW_TAGS }}
        FORCE_PUSH: ${{ vars.FORCE_PUSH }}
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: ${{ vars.GITLAB_USERNAME }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: ${{ vars.GITLAB_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
